[package]
name = "actix_scoped_example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix_scoped_derive = { version = "*", path = "../actix_scoped_derive" }
actix_scoped = { version = "*", path = "../actix_scoped" }
thiserror = { version = "1.0.50" }
actix-web = "4.4.0"
uuid = { version = "1.4.1", features = ["serde", "v4"] }
serde_json = "1.0.107"
serde = { version = "1.0.188", features = ["derive"] }
